# Use Node image as base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy Package into the files first to optimise Caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire source code into the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Install Nodemon for auto-reloading in development
RUN npm install -g nodemon

# Start the application in development mode
CMD ["nodemon", "src/index.js"]